version: '3'

services:
    mysql:
        image: mysql
        container_name: mysql
        environment: 
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: spring_boot_database
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports: 
          - 3306:3306
        volumes: 
          - spring_boot_mysql_data:/var/lib/mysql

volumes: 
  spring_boot_mysql_data: