version: '3'

services:
    mysql:
        image: mysql
        container_name: dashboard_data
        environment: 
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: dashboard_data
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports: 
          - 3306:3306
        volumes: 
          - dashboard_mysql_data:/var/lib/mysql

volumes: 
  dashboard_mysql_data: